### ISSUE TITLE
Excuse me, are the initial weights of features all 0?

### ISSUE THREAD

**Issue by szuhzw** [CMU-SAFARI/Hermes#12]
Hello. I did not see the ocp_hermes.ini file initializing the weights. Are the initial weights of features all 0?

**Comment by rahulbera** [comment]
Hi @szuhzw yes, the weights are initialized to zero. See `inc/perc_pred.h:80`.

Please create a post in the discussion section of the repository (https://github.com/CMU-SAFARI/Hermes/discussions) for further questions.
