### ISSUE TITLE
Hello. Does the "Offset" means Cacheline offeset?  Does the "CLOffset" means byte offset?

### ISSUE THREAD

**Issue by szuhzw** [CMU-SAFARI/Hermes#13]
![Uploading image.png…]()

**Comment by szuhzw** [comment]
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/3b5b4384-6fd8-41f3-9fd2-2496680f03d8)

**Comment by rahulbera** [comment]
CLoffset is the byte offset of the data within the cacheline. Please see lines 194-200 in `src/offchip_pred_perc.cc` to understand how the features are getting calculated.

Please create a post in the discussion section of the repository (https://github.com/CMU-SAFARI/Hermes/discussions) for further questions.
