### ISSUE TITLE
Hello. How to calculate the accuracy and coverage of POPET.

### ISSUE THREAD

**Issue by szuhzw** [CMU-SAFARI/Hermes#16]
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/996c53de-2308-4c06-a4fd-ab67b3ee61f8)

**Comment by rahulbera** [comment]
The accuracy and coverage measurement has been described in the appendix section of the paper.

Please create a post in the discussion section further questions like this. Opening an issue is generally used for reporting bugs or discussing improvements of the code.

**Comment by rahulbera** [comment]
Closing this issue.

**Comment by szuhzw** [comment]
Thank you.
