### ISSUE TITLE
Hello. All my *.mcpat.out file are as shown below. How to resolve it?

### ISSUE THREAD

**Issue by szuhzw** [CMU-SAFARI/Hermes#19]
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/6af46259-45d6-424e-aac1-b52749b5fd81)

**Comment by szuhzw** [comment]
I follw the experiment workflow

**Comment by rahulbera** [comment]
You can either (1) change the McPAT source code to accept a non-power-of-two cache associativity, or (2) model the nearest power-of-two cache associativity while changing the set size to keep the total size of the cache on the same ball park.
