### ISSUE TITLE
Excuse me. When I running McPAT according to the process, the following situation occurs. How to resolve it?

### ISSUE THREAD

**Issue by szuhzw** [CMU-SAFARI/Hermes#22]
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/b6a1ddaa-17bf-4ffc-8b21-02d13a98c6bb)

**Comment by hhulll** [comment]
I also encountered this problem.

**Comment by rahulbera** [comment]
@szuhzw @hhulll McPAT internally calls the CACTI model to get the energy, power, and area estimates of the declared caches. This "error" getting generated from `cacti/io.cc:1506` (https://github.com/HewlettPackard/mcpat/blob/74d4759f3ba2dff8f5a69e07a68efdb46b42fb8c/cacti/io.cc#L1506). This is an artificial limitation to CACTI, which means CACTI can very well generate estimates of any cache associativity but the authors chose to disable it by default. So, please comment out that line and recompile McPAT. It should run fine. 

Closing this issue for now. Can reopen, if needed.

**Comment by szuhzw** [comment]
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/a2dcb93b-44b2-49b2-af95-802b43da2f8e)
Excuse me. How long does this operation take?

**Comment by szuhzw** [comment]
Half an hour has passed and I still haven’t seen a generated file.

**Comment by szuhzw** [comment]
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/cb0f729d-1641-40d2-b6a5-6fd08c1d8f7c)
The problem is still not solved

**Comment by szuhzw** [comment]
@rahulbera

**Comment by szuhzw** [comment]
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/52252dd1-c9f0-440a-9654-932a30a080e9)
Excuse me. What metrics are used to analyze the performance of eight-core system in the article? Is it the average IPC for eight cores?

**Comment by szuhzw** [comment]
Hello? @rahulbera
