### ISSUE TITLE
Hello. I want to conduct an eight-core experiment with the configuration shown below. How to configure the script about "./build_champsim.sh glc multi multi multi multi 1 1 0"? 

### ISSUE THREAD

**Issue by szuhzw** [CMU-SAFARI/Hermes#24]
![image](https://github.com/CMU-SAFARI/Hermes/assets/65290731/dd29e35d-f4ec-4133-ba91-01de90f12648)

cd $HERMES_HOME
# ./build_champsim.sh <uarch> <l1d_ref> <l2c_pref> <llc_pref> <llc_repl> <ncores> <DRAM-channels> <log-DRAM-channels>
./build_champsim.sh glc multi multi multi multi 1 1 0

**Comment by szuhzw** [comment]
I  want configure 4cores, 2channels, and 1ranks per channel. Is "./build_champsim.sh glc multi multi multi multi 4 2 0" right?

**Comment by rahulbera** [comment]
Hi @szuhzw, as the `build_champsim.sh` [script](https://github.com/CMU-SAFARI/Hermes/blob/0cf5f8c2ee15358703bf34324dc1a9147b1a324a/build_champsim.sh#L5) says, the last three arguments are: number of cores, num_dram_channels, and log_num_dram_cnannels. So in your case, you have set it as `4 2 1`.

Note that, if you are using `inc/uarch/glc.h` micro-arch, it already uses [1 rank per DRAM channel](https://github.com/CMU-SAFARI/Hermes/blob/0cf5f8c2ee15358703bf34324dc1a9147b1a324a/inc/uarch/glc.h#L130). You can change manually if you want to set different ranks/channel.

**Comment by szuhzw** [comment]
Thank you.

**Comment by szuhzw** [comment]
Hi. @rahulbera Could you tell me what “log_num_dram_channels” means in the microarchitecture configuration mentioned in the article?
![image](https://github.com/user-attachments/assets/8914a190-3c4b-42d1-8431-961385b57afd)

**Comment by szuhzw** [comment]
Is "How much rank per channel" right?
