### ISSUE TITLE
Hello. When I run the trace generated by me, it shows a failure like below. Please tell me what is the reason for this and how to solve it?

### ISSUE THREAD

**Issue by szuhzw** [CMU-SAFARI/Hermes#25]

**Comment by rahulbera** [comment]
This error seems to be stemming from the trace file itself, not from Hermes implementation. For some reason your trace file doesn't contain virtual address (VA) of memory request. Hence the error.

I am assuming that you're using the PIN tool provided by ChampSim repo to generate this trace. In that case, try running this trace via the mainline ChampSim (https://github.com/ChampSim/ChampSim). If the mainline ChampSim also fails running it (which I feel it would), then you may need to make necessary changes in the PIN tool to capture VA of memory requests from HPCG workloads.
